include: package:flutter_lints/flutter.yaml

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options


## Defines a default set of lint rules enforced for
## projects at Google. For details and rationale,
## see https://github.com/dart-lang/pedantic#enabled-lints.
#include: package:pedantic/analysis_options.yaml
#
## For lint rules and documentation, see http://dart-lang.github.io/linter/lints.
## Uncomment to specify additional rules.
#linter:
#  rules:
#    prefer_final_fields: false
#    unawaited_futures: false
#
#analyzer:
#  exclude:
#    - example
#    - lib/**/*.g.dart

analyzer:
  exclude:
    - lib/**/*.g.dart
