name: sendbird_chat_sdk
description: Sendbird Chat SDK
version: 4.0.0
homepage: https://sendbird.com
repository: https://github.com/sendbird/sendbird-chat-sdk-flutter
documentation: https://sendbird.com/docs/chat/v4/flutter/getting-started/send-first-message

environment:
  sdk: '>=2.17.0 <4.0.0'
  flutter: '>=2.11.0'

platforms:
  android:
  ios:
  web:

dependencies:
  flutter:
    sdk: flutter
  collection: ^1.17.0
  uuid: ^3.0.7
  json_annotation: ^4.8.0
  encrypt: ^5.0.1
  shared_preferences: ^2.1.0
  http: ^0.13.5
  logger: ^1.3.0
  mime: ^1.0.4
  connectivity_plus: ^3.0.4
  http_parser: ^4.0.2
  web_socket_channel: ^2.4.0
  universal_io: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  test: ^1.21.4
  stack_trace: ^1.11.0
  json_serializable: ^6.6.1
  build_runner: ^2.3.3
